apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: b9g34innc-nodejs
  janus-idp.io/tekton: b9g34innc-nodejs
  backstage.io/kubernetes-id: b9g34innc-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: b9g34innc-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
